airflowVersion: "3.2.2"

apiSecretKey: "51fed262-a647-4ca5-81df-b4b1eba38b9d"

jwtSecret: "48fe8dbd-b038-41ae-ba0e-b4e00fa60400"

executor: "KubernetesExecutor"

#Images
images:
  airflow:
    repository: my-dags
    tag: ~
    digest: ~
    pullPolicy: IfNotPresent
dags:
  gitSync:
    enabled: true

    # Git repo clone url
    repo: https://github.com/yapkarhui2000/Databricks-airflow3.0-kubernetes.git
    # SSH example: git@github.com:apache/airflow.git
    # HTTPS example: https://github.com/apache/airflow.git

    branch: main
    rev: HEAD

    # The git revision (branch, tag, or hash) to check out, v4 only
    ref: main

    depth: 1

    # The number of consecutive failures allowed before aborting
    maxFailures: 0

    # Subpath within the repo where dags are located.
    # Should be "" if dags are at repo root
    subPath: "dags"
    credentialsSecret: git-credentials

logs:
  persistence:
    enabled: true
    storageClassName: manual
    existingClaim: airflow-logs-pvc
