apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: eWFwa2FyaHVpMjAwMA==
  GITSYNC_PASSWORD: Z2hwXzV3VWd0Qnd6TEU4T0VZNm81Q1dUSUNQVVRsUTlqcDA1OE5OMw==
  GIT_SYNC_USERNAME: eWFwa2FyaHVpMjAwMA==
  GIT_SYNC_PASSWORD: Z2hwXzV3VWd0Qnd6TEU4T0VZNm81Q1dUSUNQVVRsUTlqcDA1OE5OMw==
